apiVersion: v1
kind: Service
metadata:
  name: hive-trader-engine
  namespace: hive-trader
  labels:
    app: hive-trader-engine
spec:
  selector:
    app: hive-trader-engine
  ports:
    - name: http
      port: 80
      targetPort: 8080
